import './globals.css'

export const metadata = {
  title: 'RESUME - IHS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title> RESUME - IHS</title>
      </head>
    <body className='bg-gradient-to-r from-teal-50 to-teal-100'>{children}</body>
    </html>
  )
}
